---
title: "Untitled"
author: "Indra Boving"
date: "8/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
here = here::here
library(corrplot)
select = dplyr::select
col3 = hcl.colors(10, "YlOrRd", rev = TRUE) #color scale to use for consistency 
```

#Local - data wrangling: 
```{r}
hp.local.df <- read.csv(here("processed-data/hp.ignite.only.LOCAL.csv")) %>%  mutate(lfm = lfm.NAs.imputed) 
epi.local.df <- read.csv(here("processed-data/epi.ignite.only.LOCAL.csv")) %>%  mutate(lfm = lfm.NAs.imputed)

#make wide dataset, used to determine which 
local.wide.df <- merge(hp.local.df, epi.local.df, by.x = c("sample", "individual", "hydration", "season",  "lfm.outliers.out", "site", "month", "year", "spp","bins5lfm", "bins10lfm", "bins20lfm", "year.month", "RWD", "RWC", "max.mpa.sample", "precip.2month", "precip.2mo", "gr"), by.y =  c("sample", "individual", "hydration", "season", "lfm.outliers.out", "site", "month", "year", "spp","bins5lfm",  "bins10lfm", "bins20lfm", "year.month", "RWD", "RWC", "max.mpa.sample", "precip.2month", "precip.2mo", "gr"), all = F, suffixes = c(".hp",".epi"))

#Make long dataset:

epi.long.local.df <- local.wide.df %>% 
select("sample", "individual", "hydration", "season",  "lfm.outliers.out", "site", "month", "year", "spp","bins5lfm", "bins10lfm", "bins20lfm", "year.month", "RWD", "RWC", "max.mpa.sample", "precip.2month", "precip.2mo", "gr" | ends_with(".epi")) %>% 
 rename_with(~str_remove(., '.epi'))

hp.long.local.df <- local.wide.df %>% 
select("sample", "individual", "hydration", "season",  "lfm.outliers.out", "site", "month", "year", "spp","bins5lfm", "bins10lfm", "bins20lfm", "year.month", "RWD", "RWC", "max.mpa.sample", "precip.2month", "precip.2mo", "gr" | ends_with(".hp")) %>% 
 rename_with(~str_remove(., '.hp'))

local.long.df <- rbind(epi.long.local.df, hp.long.local.df) %>%  select("sample","individual","model","site","month","year","spp","hydration","mpa","lfm","lfm.outliers.out", "bins5lfm","bins10lfm","bins20lfm","year.month","ww.flam.sample","dw.flam.sample","sample.wt","start.temp","temp.change","temp.max","ignition.temp","prop.new","fd","fh","gd","glow","gti","pfg","prop.ignite","ros","round","ttfg","tti","flam.index","ignition")

write.csv(x = local.long.df, (here("processed-data/method.comparison.local.csv"))) 
```

#SEKI - data wrangling: 

```{r}
hp.seki.df <- read.csv(here("processed-data", "hp.ignite.only.seki.csv")) %>%  mutate(lfm = lfm.NAs.imputed) 
epi.seki.df <- read.csv(here("processed-data", "epi.ignite.only.seki.csv")) %>%  mutate(lfm = lfm.NAs.imputed) 

str(epi.seki.df)

seki.df <- rbind(hp.seki.df, epi.seki.df) 

seki.wide.groups.df <- merge(epi.seki.df, hp.seki.df, by.x = c("individual", "sample", "gr", "site", "month", "year","spp"), by.y =  c("individual", "sample", "gr", "site", "month", "year", "spp"), all - F,suffixes = c(".epi",".hp")) %>% 
  select(mpa.epi, mpa.hp, lfm.NAs.imputed.epi, lfm.NAs.imputed.hp, individual, gr, lfm.outliers.out.epi, lfm.outliers.out.hp)

seki.wide.df <- merge(epi.seki.df, hp.seki.df, by.x = c("sample", "individual","site", "month", "year","spp","bins5lfm",  "bins10lfm", "bins20lfm", "year.month", "RWD", "RWC", "max.mpa.sample"), by.y =  c("sample", "individual","site", "month", "year", "spp","bins5lfm",  "bins10lfm", "bins20lfm", "year.month", "RWD", "RWC", "max.mpa.sample"), suffixes = c(".epi",".hp"))

epi.long.seki.df <- seki.wide.df %>% 
select("sample", "individual","site", "month", "year","spp","bins5lfm",  "bins10lfm", "bins20lfm", "year.month", "RWD", "RWC", "max.mpa.sample" | ends_with(".epi")) %>% 
 rename_with(~str_remove(., '.epi'))

hp.long.seki.df <- seki.wide.df %>% 
select("sample", "individual","site", "month", "year","spp","bins5lfm",  "bins10lfm", "bins20lfm", "year.month", "RWD", "RWC", "max.mpa.sample" | ends_with(".hp")) %>% 
 rename_with(~str_remove(., '.hp'))

seki.long.df <- dplyr::bind_rows(epi.long.seki.df, hp.long.seki.df) %>% 
  dplyr::select("sample","individual","model","site","month","year","spp","hydration","mpa","lfm","lfm.outliers.out", "bins5lfm","bins10lfm","bins20lfm","year.month","ww.flam.sample","dw.flam.sample","sample.wt","start.temp","temp.change","temp.max","ignition.temp","prop.new","fd","fh","gd","glow","gti","pfg","prop.ignite","ros","round","ttfg","tti","ttms","flam.index","ignition") 

write.csv(x = seki.long.df, (here("processed-data/method.comparison.seki.csv"))) 
```
#Local - corrplots: 
````{r}
corrplot.flam.data.hp <- local.long.df %>% 
filter(model == "HP") %>% 
  dplyr::select(tti, fh, fd, gd, temp.max, prop.ignite, lfm, sample.wt, dw.flam.sample, mpa) %>% 
  drop_na() %>% 
  mutate("Time to Ignition" = as.numeric(tti)) %>% 
  mutate("Flame Height" = fh) %>%
  mutate("Flame Duration" = as.numeric(fd)) %>%
  mutate("Glow Duration" = as.numeric(gd)) %>%
  mutate("Maximum Temp." = as.numeric(temp.max)) %>%
  mutate("Dry Weight" = as.numeric(dw.flam.sample)) %>%
  mutate("Sample Weight" = as.numeric(sample.wt)) %>% 
  mutate("Proportion Ignited" = as.numeric(prop.ignite)) %>%
  mutate("LFM" = as.numeric(lfm)) %>% 
  mutate("Water Potential" = as.numeric(mpa)) %>% 
  #mutate("Time to Max Spread" = as.numeric(ttms)) %>% 
  dplyr::select(-tti, -fh, -fd, -gd, -temp.max, -prop.ignite, -lfm, -sample.wt, -dw.flam.sample, -mpa)

cfd2.hp <- cor(corrplot.flam.data.hp)

corrplot(cfd2.hp, method = 'color', order = 'alphabet', col = col3, tl.col = 'black', add = FALSE, is.corr = FALSE, diag = TRUE, addCoef.col = 'black',  type = "upper", title = "Hot Plate Method") +
  theme_bw()

corrplot.flam.data.epi <- local.long.df %>% 
  filter(model == "EPI") %>% 
  dplyr::select(tti, fh, fd, gd, temp.max, prop.ignite, lfm, sample.wt, dw.flam.sample, mpa) %>% 
    drop_na() %>% 
  mutate("Time to Ignition" = as.numeric(tti)) %>% 
  mutate("Flame Height" = fh) %>%
  mutate("Flame Duration" = as.numeric(fd)) %>%
  mutate("Glow Duration" = as.numeric(gd)) %>%
  mutate("Maximum Temp." = as.numeric(temp.max)) %>%
  mutate("Dry Weight" = as.numeric(dw.flam.sample)) %>%
  mutate("Sample Weight" = as.numeric(sample.wt)) %>% 
  mutate("Proportion Ignited" = as.numeric(prop.ignite)) %>%
  mutate("LFM" = as.numeric(lfm)) %>% 
  mutate("Water Potential" = as.numeric(mpa)) %>% 
  #mutate("Time to Max Spread" = as.numeric(ttms)) %>% 
  dplyr::select(-tti, -fh, -fd, -gd, -temp.max, -prop.ignite, -lfm, -sample.wt, -dw.flam.sample, -mpa)

cfd2.epi <- cor(corrplot.flam.data.epi)

corrplot(cfd2.epi, method = 'color', order = 'alphabet', col = col3, tl.col = 'black', add = FALSE, is.corr = FALSE, diag = TRUE, addCoef.col = 'black',  type = "upper", title = "Epi Method") +
  theme_bw()
```
#SEKI - corrplots: 
```{r}
corrplot.flam.data.hp <- seki.long.df %>% 
  filter(model == "HP") %>% 
  dplyr::select(tti, fh, fd, gd, temp.max, prop.ignite, lfm, sample.wt, dw.flam.sample, mpa) %>% 
  drop_na() %>% 
  mutate("Time to Ignition" = as.numeric(tti)) %>% 
  mutate("Flame Height" = fh) %>%
  mutate("Flame Duration" = as.numeric(fd)) %>%
  mutate("Glow Duration" = as.numeric(gd)) %>%
  mutate("Maximum Temp." = as.numeric(temp.max)) %>%
  mutate("Dry Weight" = as.numeric(dw.flam.sample)) %>%
  mutate("Sample Weight" = as.numeric(sample.wt)) %>% 
  mutate("Proportion Ignited" = as.numeric(prop.ignite)) %>%
  mutate("LFM" = as.numeric(lfm)) %>% 
  mutate("Water Potential" = as.numeric(mpa)) %>% 
  #mutate("Time to Max Spread" = as.numeric(ttms)) %>% 
  dplyr::select(-tti, -fh, -fd, -gd, -temp.max, -prop.ignite, -lfm, -sample.wt, -dw.flam.sample, -mpa)

cfd2.hp <- cor(corrplot.flam.data.hp)

corrplot(cfd2.hp, method = 'color', order = 'alphabet', col = col3, tl.col = 'black', add = FALSE, is.corr = FALSE, diag = TRUE, addCoef.col = 'black',  type = "upper", title = "Hot Plate Method") +
  theme_bw()

corrplot.flam.data.epi <- seki.long.df %>% 
  filter(model == "EPI") %>% 
  dplyr::select(tti, fh, fd, gd, temp.max, prop.ignite, lfm, sample.wt, dw.flam.sample, mpa) %>% 
    drop_na() %>% 
  mutate("Time to Ignition" = as.numeric(tti)) %>% 
  mutate("Flame Height" = fh) %>%
  mutate("Flame Duration" = as.numeric(fd)) %>%
  mutate("Glow Duration" = as.numeric(gd)) %>%
  mutate("Maximum Temp." = as.numeric(temp.max)) %>%
  mutate("Dry Weight" = as.numeric(dw.flam.sample)) %>%
  mutate("Sample Weight" = as.numeric(sample.wt)) %>% 
  mutate("Proportion Ignited" = as.numeric(prop.ignite)) %>%
  mutate("LFM" = as.numeric(lfm)) %>% 
  mutate("Water Potential" = as.numeric(mpa)) %>% 
  #mutate("Time to Max Spread" = as.numeric(ttms)) %>% 
  dplyr::select(-tti, -fh, -fd, -gd, -temp.max, -prop.ignite, -lfm, -sample.wt, -dw.flam.sample, -mpa)

cfd2.epi <- cor(corrplot.flam.data.epi)

corrplot(cfd2.epi, method = 'color', order = 'alphabet', col = col3, tl.col = 'black', add = FALSE, is.corr = FALSE, diag = TRUE, addCoef.col = 'black',  type = "upper", title = "Epi Method") +
  theme_bw()
```
#Local - PCA:
```{r}
cat.epi.flamdata <-  local.long.df %>% 
   mutate("Water Status"= cut(lfm, breaks = c(0, 80, 400), labels = c("< 79% LFM", "> 79% LFM"))) %>%
  mutate(Species = spp) %>% 
  select(c("hydration", "spp", "year.month", "sample", "Water Status", "model")) 
str(cat.epi.flamdata)

pca.flam.data <- local.long.df %>% 
  dplyr::select(tti, fh, fd, gd, temp.max, prop.ignite, lfm, sample.wt, dw.flam.sample, mpa) %>% 
    drop_na() %>% 
  mutate("Time to Ignition" = as.numeric(tti)) %>% 
  mutate("Flame Height" = fh) %>%
  mutate("Flame Duration" = as.numeric(fd)) %>%
  mutate("Glow Duration" = as.numeric(gd)) %>%
  mutate("Maximum Temp." = as.numeric(temp.max)) %>%
  mutate("Dry Weight" = as.numeric(dw.flam.sample)) %>%
  mutate("Sample Weight" = as.numeric(sample.wt)) %>% 
  mutate("Proportion Ignited" = as.numeric(prop.ignite)) %>%
  mutate("LFM" = as.numeric(lfm)) %>% 
  mutate("Water Potential" = as.numeric(mpa)) %>% 
  #mutate("Time to Max Spread" = as.numeric(ttms)) %>% 
  dplyr::select(-tti, -fh, -fd, -gd, -temp.max, -prop.ignite, -lfm, -sample.wt, -dw.flam.sample, -mpa)

str(pca.flam.data)

epi.flamdata.pca <- prcomp(na.omit(pca.flam.data), center = TRUE, scale = TRUE) 
str(epi.flamdata.pca)

print(epi.flamdata.pca)
summary(epi.flamdata.pca)

pca.plot <- ggbiplot::ggbiplot(epi.flamdata.pca, groups = cat.epi.flamdata$model, 
                        circle = F, 
                        varname.size = 3, 
                        alpha = .6, 
                        labels.size = 5,
                        varname.adjust = 1.2, 
                        repel = T, 
                        col = cat.epi.flamdata$LFM.20) +
  labs(x = "PC1", y = "PC2)") +
  #ggtitle(expression(paste("Flammability of ", italic("A. fasciculatum "), #"and", italic(" C. megacarpus")))) +
  labs(color = "Model", size = 40) +
  #theme(plot.title = element_text(size = 55, face = "bold")) +
  #ordiplot(PCA) +
  theme_bw() + 
  theme(plot.title = element_text(size = 50, face = "bold"))
pca.plot
```
#SEKI - PCA
```{r}
cat.epi.flamdata <-  seki.long.df %>% 
   mutate("Water Status"= cut(lfm, breaks = c(0, 80, 400), labels = c("< 79% LFM", "> 79% LFM"))) %>%
  mutate(Species = spp) %>% 
  select("hydration", "spp", "year.month", "sample", "Water Status", "model", tti, fh, fd, gd, temp.max, prop.ignite, lfm, sample.wt, dw.flam.sample, mpa) %>% 
  drop_na() %>% 
  select(c("hydration", "spp", "year.month", "sample", "Water Status", "model")) 
str(cat.epi.flamdata)

pca.flam.data <- seki.long.df %>% 
  dplyr::select(tti, fh, fd, gd, temp.max, prop.ignite, lfm, sample.wt, dw.flam.sample, mpa) %>% 
  drop_na() %>% 
  mutate("Time to Ignition" = as.numeric(tti)) %>% 
  mutate("Flame Height" = fh) %>%
  mutate("Flame Duration" = as.numeric(fd)) %>%
  mutate("Glow Duration" = as.numeric(gd)) %>%
  mutate("Maximum Temp." = as.numeric(temp.max)) %>%
  mutate("Dry Weight" = as.numeric(dw.flam.sample)) %>%
  mutate("Sample Weight" = as.numeric(sample.wt)) %>% 
  mutate("Proportion Ignited" = as.numeric(prop.ignite)) %>%
  mutate("LFM" = as.numeric(lfm)) %>% 
  mutate("Water Potential" = as.numeric(mpa)) %>% 
  #mutate("Time to Max Spread" = as.numeric(ttms)) %>% 
  dplyr::select(-tti, -fh, -fd, -gd, -temp.max, -prop.ignite, -lfm, -sample.wt, -dw.flam.sample, -mpa)

str(pca.flam.data)

epi.flamdata.pca <- prcomp(na.omit(pca.flam.data), center = TRUE, scale = TRUE) 
str(epi.flamdata.pca)

print(epi.flamdata.pca)
summary(epi.flamdata.pca)

pca.plot <- ggbiplot::ggbiplot(epi.flamdata.pca, groups = cat.epi.flamdata$model, 
                        circle = F, 
                        varname.size = 3, 
                        alpha = .6, 
                        labels.size = 5,
                        varname.adjust = 1.2, 
                        repel = T, 
                        col = cat.epi.flamdata$model) +
  labs(x = "PC1", y = "PC2)") +
  #ggtitle(expression(paste("Flammability of ", italic("A. fasciculatum "), #"and", italic(" C. megacarpus")))) +
  labs(color = "Model", size = 40) +
  #theme(plot.title = element_text(size = 55, face = "bold")) +
  #ordiplot(PCA) +
  theme_bw() + 
  theme(plot.title = element_text(size = 50, face = "bold"))
pca.plot
```
#Local - tti plots
```{r}
mpa.lfm.plot.2020 <- local.long.df %>% 
  ggplot(aes(x = mpa, y = tti, color = -mpa)) +  geom_point(size = 1) +
  scale_color_gradient(low = "goldenrod", high = "deepskyblue1") +
  geom_smooth(method = lm, se = F, size = 0.5, color = "royalblue4") +
  stat_regline_equation(label.x=5, label.y=150) +
  stat_cor(aes(label=..rr.label..), label.x=5, label.y=140) +
  facet_grid(~model) +
  theme(strip.text.x = element_text(size = 10)) +
  labs(y = "Time to Ignition (sec)", x = "Water Potential (-Mpa)") +
  theme_bw()
mpa.lfm.plot.2020
```
#SEKI - tti plots
```{r}
mpa.lfm.plot.2020 <- seki.long.df %>% 
  ggplot(aes(x = mpa, y = tti, color = -mpa)) +  geom_point(size = 1) +
  scale_color_gradient(low = "goldenrod", high = "deepskyblue1") +
  geom_smooth(method = lm, se = F, size = 0.5, color = "royalblue4") +
  stat_regline_equation(label.x=5, label.y=150) +
  stat_cor(aes(label=..rr.label..), label.x=5, label.y=140) +
  facet_grid(~model) +
  theme(strip.text.x = element_text(size = 10)) +
  labs(y = "Time to Ignition (sec)", x = "Water Potential (-Mpa)") +
  theme_bw()
mpa.lfm.plot.2020
```
#Local - fh plots
```{r}
mpa.lfm.plot.2020 <- local.long.df %>% 
  filter(ignition == 1 | 2) %>% 
  ggplot(aes(x = mpa, y = fh, color = -mpa)) +  geom_point(size = 1) +
  scale_color_gradient(low = "goldenrod", high = "deepskyblue1") +
  geom_smooth(method = lm, se = F, size = 0.5, color = "royalblue4") +
  stat_regline_equation(label.x=5, label.y=35) +
  stat_cor(aes(label=..rr.label..), label.x=5, label.y=40) +
  facet_grid(~model) +
  theme(strip.text.x = element_text(size = 10)) +
  labs(y = "Flame Height (cm)", x = "Water Potential (-Mpa)") +
  theme_bw()
mpa.lfm.plot.2020
```
#SEKI - fh plots
```{r}
mpa.lfm.plot.2020 <- seki.long.df %>% 
  filter(ignition == 1 | 2) %>% 
  ggplot(aes(x = mpa, y = fh, color = -mpa)) +  geom_point(size = 1) +
  scale_color_gradient(low = "goldenrod", high = "deepskyblue1") +
  geom_smooth(method = lm, se = F, size = 0.5, color = "royalblue4") +
  stat_regline_equation(label.x=5, label.y=35) +
  stat_cor(aes(label=..rr.label..), label.x=5, label.y=40) +
  facet_grid(~model) +
  theme(strip.text.x = element_text(size = 10)) +
  labs(y = "Flame Height (cm)", x = "Water Potential (-Mpa)") +
  theme_bw()
mpa.lfm.plot.2020
```
#Local - multiplot
```{r}
local.long.df %>%
  dplyr::select(tti, fh, fd, gd, prop.ignite, lfm, sample.wt, mpa, model, gti, ttfg, flam.index, temp.change, pfg, lfm) %>% 
  gather(-mpa, -model,key = "var", value = "value") %>%
  ggplot(aes(x = value, y = mpa, color = model)) +
    geom_point(size = 1) +
    facet_wrap(~ var, scales = "free") +
    theme_bw()
```
#SEKI - multiplot
```{r}
seki.long.df %>%
  dplyr::select(tti, fh, fd, gd, prop.ignite, lfm, sample.wt, mpa, model, gti, ttfg, flam.index, temp.change, pfg, lfm) %>% 
  gather(-mpa, -model,key = "var", value = "value") %>%
  ggplot(aes(x = value, y = mpa, color = model)) +
    geom_point(size = 1) +
    facet_wrap(~ var, scales = "free") +
    theme_bw()
```